# Credencial de git do Kargo (reusa o PAT do Backstage).
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gitops-demo-java-repo
  namespace: demo-java
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-homelab
    kind: ClusterSecretStore
  target:
    name: gitops-demo-java-repo
    template:
      metadata:
        labels:
          kargo.akuity.io/cred-type: git
      data:
        repoURL: https://github.com/tourinho-labs/gitops-demo-java.git
        username: kargo                 # GitHub ignora o user quando a senha é PAT válido
        password: "{{ .token }}"
  data:
    - secretKey: token
      remoteRef:
        key: cluster/backstage
        property: github_token
